### ISSUE TITLE
CITY_OR_REGION

### ISSUE THREAD

**Issue by frek666** [Witaly3/avito-parser-selenium#1]
### код работает абсолютно с любым городом, кроме Москвы? Не могу понять в чем проблема...
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\avito-parser-selenium-main\avitoparser.py", line 109, in <module>
    avito_parser()
  File "C:\Users\admin\Desktop\avito-parser-selenium-main\avitoparser.py", line 50, in avito_parser
    count = int(driver.find_element(by=By.CSS_SELECTOR,
ValueError: invalid literal for int() with base 10: '4 512'

**Comment by Witaly3** [comment]
код работает и с москвой. ошибку исправил
